# Generated by Django 3.1.5 on 2021-01-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cId', models.IntegerField()),
                ('name', models.CharField(max_length=10)),
                ('teacher', models.CharField(max_length=10)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('fees', models.IntegerField()),
            ],
        ),
    ]
