# Generated by Django 3.1.5 on 2021-01-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210112_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='internships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('hr', models.CharField(max_length=20)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('stipend', models.IntegerField()),
            ],
        ),
    ]
